name: flutter_quran_app
description: "Quran App."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.11+21

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8 
  device_info_plus: 11.3.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_intro: ^3.4.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: 2.4.4
  flutter_qiblah: ^3.1.0+1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  geocoding: ^4.0.0
  geolocator: ^13.0.2
  get_it: ^8.2.0
  google_fonts: 6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: 0.20.2
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17
  lottie: 3.3.1
  permission_handler: ^12.0.1
  quran:
    path: ./packages/quran-1.2.2
  shared_preferences: ^2.5.3
  toastification: ^3.0.3
  vector_graphics: ^1.1.19
  vibration: ^3.1.4
  wakelock_plus: ^1.4.0
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  flutter_lints: 2.0.3
  vector_graphics_compiler: 1.1.18

  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/
    - assets/svgs/
    - path: assets/sections/
      transformers:
        - package: vector_graphics_compiler
    - assets/lotties/
    - assets/fonts/qcf4/
    - shorebird.yaml

  fonts:
    - family: uthmanic
      fonts:
        - asset: assets\fonts\UthmanTN1-Ver10.otf
    - family: Harmattan
      fonts:
        - asset: assets\fonts\Harmattan-Regular.ttf
          weight: 400
        - asset: assets\fonts\Harmattan-Medium.ttf
          weight: 500
        - asset: assets\fonts\Harmattan-Bold.ttf
          weight: 700

    - family: ExpoArabic
      fonts:
        - asset: assets\fonts\ExpoArabic-Book.ttf
        - asset: assets\fonts\ExpoArabic-Bold.ttf
          weight: 700
    - family: BFantezy
      fonts:
        - asset: assets\fonts\BFantezy-Regular.ttf

flutter_assets:
  assets_path:
    - assets/images/
    - assets/svgs/
    - assets/sections/
    - assets/lotties/

  output_path: lib/core/theme/
  filename: app_assets.dart
  field_prefix: null
  classname: AppAssets

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/quran_ic_launcher.png"
  min_sdk_android: 23
